apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    control-plane: platform-operator
spec:
  selector:
    matchLabels:
      control-plane: platform-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: platform-operator
    spec:
      serviceAccountName: operator
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        - --annotations=foo.flanksource.com/bar,foo.flanksource.com/baz
        image: "docker.io/flanksource/platform-operator:latest"
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
