version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/flanksource/platform-operator
    steps:
      - checkout
      - setup_remote_docker
      - run: make release

workflows:
  version: 2
  build:
    jobs:
      - release:
          context: Github
          filters:
            tags:
              only: /.*/
