version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/flanksource/platform-operator
    steps:
      - checkout
      - setup_remote_docker
      - run: make ci-release IMG=flanksource/platform-operator TAG=$(date +%Y%m%d%M%H%M%S)

workflows:
  version: 2
  build:
    jobs:
      - release:
          context: Github
          filters:
            tags:
              only: /.*/
