# permissions to do viewer clusterresourcequotas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterresourcequota-viewer-role
rules:
  - apiGroups:
      - platform.flanksource.com
    resources:
      - clusterresourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - platform.flanksource.com
    resources:
      - clusterresourcequotas/status
    verbs:
      - get
