# permissions to do edit clusterresourcequotas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterresourcequota-editor-role
rules:
  - apiGroups:
      - platform.flanksource.com
    resources:
      - clusterresourcequotas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - platform.flanksource.com
    resources:
      - clusterresourcequotas/status
    verbs:
      - get
      - patch
      - update
