apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-additional
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-operator-additional
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-configmap
  namespace: system
subjects:
- kind: ServiceAccount
  name: operator
  namespace: system
roleRef:
  kind: Role
  name: manager-configmap
  apiGroup: rbac.authorization.k8s.io
