---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-operator
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-operator
subjects:
  - kind: ServiceAccount
    name: platform-operator
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: platform-operator
  template:
    metadata:
      labels:
        name: platform-operator
    spec:
      serviceAccountName: platform-operator
      containers:
        - name: platform-operator
          image: docker.io/flanksource/platform-operator:0.1
          command:
            - /platform-operator serve -watch-interval 5m
