# Adds namespace to all resources.
namespace: platform-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: platform-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

resources:
  - "namespace.yaml"

patchesStrategicMerge:
  - cainjection_in_clusterresourcequotas.yaml
  - webhookcainjection_patch.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

bases:
  - ../../crds
  - ../rbac
  - ../manager
  - ../webhook
  - ../certmanager

vars:
  # [CERTMANAGER]
  - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
    fieldref:
      fieldpath: metadata.namespace
  - name: CERTIFICATE_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: operator
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: operator
